### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by MesaBlack** [smb123w64gb/vtfTrans-rs#1]

**Comment by smb123w64gb** [comment]
You should be able to cargo build --release on linux. Just a install of rust should do.

**Comment by MesaBlack** [comment]
detailed instructions?

**Comment by MesaBlack** [comment]
how do you cargo build this?

**Comment by smb123w64gb** [comment]
1.Cargo is the package manager for the language [Rust](https://www.rust-lang.org/). So you first need to install rust to compile the executable.
2.Git is recommended to download from Github and any other repository service.

Once you have Rust and Git installed it should be a matter of first
git clone https://github.com/smb123w64gb/vtfTrans-rs.git
cd vtfTrans-rs
cargo build --release 

Once you compiled it you should find it in .\vtfTrans-rs\target\release
![image](https://github.com/smb123w64gb/vtfTrans-rs/assets/4001226/e7448b54-cf96-494a-b7cb-4d1d00a0790f)

**Comment by MesaBlack** [comment]
Hrmmmm...
![image](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/e633cfb5-d07f-40fa-a158-a8ce5f0ff494)

**Comment by MesaBlack** [comment]
![image](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/3f62f403-105b-4a1c-9690-9515f712f023)

**Comment by MesaBlack** [comment]
![image](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/1d12584e-4db0-43b9-89b2-0885468b4b88)

**Comment by MesaBlack** [comment]
![Screenshot 2023-08-08 8 23 16 AM](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/8cbb712e-a353-49e8-a2aa-9b9d4a0d86db)

**Comment by MesaBlack** [comment]
![Screenshot 2023-08-08 7 57 45 AM](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/174c7ce5-dd32-4f33-980d-e84b185be431)

**Comment by MesaBlack** [comment]
![Screenshot 2023-08-08 7 57 45 AM](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/38936965-c21f-4f47-9201-a7b894fb213a)

**Comment by MesaBlack** [comment]
ay, wait!

**Comment by MesaBlack** [comment]
I think I need a bit of help.

**Comment by MesaBlack** [comment]
I've tried target release and...

**Comment by MesaBlack** [comment]
![image](https://github.com/smb123w64gb/vtfTrans-rs/assets/132141735/14a181cf-b5a7-44e4-b7c3-24fce578477b)
